apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-internal
resources:
  - deploy.yaml
patches:
  - ingress-controller-patch.yml
  - ingress-controller-svc-patch.yml
